theme: jekyll-theme-minimal
title: "Mitta Bhavya Switha - Java Developer"
description: "Dive into my resume to learn about my journey as a Java Developer. Here, you can explore my skills, professional experience, and key projects that highlight my expertise in building robust applications. I'm passionate about technology and always eager to take on new challenges!"
